### ISSUE TITLE
PretrainedTransformerMismatchedIndexer _add_encoding_to_vocabulary_if_needed is broken

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allennlp#4515]
the tokenizers library doesn't take into account that self._tokenizer might be a dictionary 
```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-7f51839e03f5> in <module>
      2 for inst in train_dataset:
      3     a = inst
----> 4     res_list = model.forward_on_instances([inst])
      5     print(res_list)
      6 #     break

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/models/model.py in forward_on_instances(self, instances)
    168             cuda_device = self._get_prediction_device()
    169             dataset = Batch(instances)
--> 170             dataset.index_instances(self.vocab)
    171             model_input = util.move_to_device(dataset.as_tensor_dict(), cuda_device)
    172             outputs = self.make_output_human_readable(self(**model_input))

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/data/batch.py in index_instances(self, vocab)
    157     def index_instances(self, vocab: Vocabulary) -> None:
    158         for instance in self.instances:
--> 159             instance.index_fields(vocab)
    160 
    161     def print_statistics(self) -> None:

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/data/instance.py in index_fields(self, vocab)
     73             self.indexed = True
     74             for field in self.fields.values():
---> 75                 field.index(vocab)
     76 
     77     def get_padding_lengths(self) -> Dict[str, Dict[str, int]]:

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/data/fields/text_field.py in index(self, vocab)
     66         self._indexed_tokens = {}
     67         for indexer_name, indexer in self._token_indexers.items():
---> 68             self._indexed_tokens[indexer_name] = indexer.tokens_to_indices(self.tokens, vocab)
     69 
     70     @overrides

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py in tokens_to_indices(self, tokens, vocabulary)
     61     @overrides
     62     def tokens_to_indices(self, tokens: List[Token], vocabulary: Vocabulary) -> IndexedTokenList:
---> 63         self._matched_indexer._add_encoding_to_vocabulary_if_needed(vocabulary)
     64 
     65         wordpieces, offsets = self._allennlp_tokenizer.intra_word_tokenize([t.text for t in tokens])

/home/ohad/.conda/cap/lib/python3.7/site-packages/allennlp/data/token_indexers/pretrained_transformer_indexer.py in _add_encoding_to_vocabulary_if_needed(self, vocab)
     72 
     73         try:
---> 74             vocab_items = self._tokenizer.get_vocab().items()
     75         except NotImplementedError:
     76             vocab_items = (

/home/ohad/.conda/cap/lib/python3.7/site-packages/transformers/tokenization_utils.py in get_vocab(self)
   2368 
   2369     def get_vocab(self):
-> 2370         return self._tokenizer.get_vocab(True)
   2371 
   2372     def convert_tokens_to_string(self, tokens: List[int], skip_special_tokens: bool = False) -> str:

/home/ohad/.conda/cap/lib/python3.7/site-packages/tokenizers/implementations/base_tokenizer.py in get_vocab(self, with_added_tokens)
     36             The vocabulary
     37         """
---> 38         return self._tokenizer.get_vocab(with_added_tokens=with_added_tokens)
     39 
     40     def get_vocab_size(self, with_added_tokens: bool = True) -> int:

AttributeError: 'dict' object has no attribute 'get_vocab'
```

**Comment by OhadRubin** [comment]
A temporary fix is the following:
```
        # try:
        #     vocab_items = self._tokenizer[self._namespace].get_vocab().items()
        # except NotImplementedError:
        vocab_items = (
            (self._tokenizer.convert_ids_to_tokens(idx), idx)
            for idx in range(self._tokenizer.vocab_size)
        )
```

**Comment by OhadRubin** [comment]
This is solved if I change the model to bert-base-uncased, so this is probably a bug in the hugginface code.
Closed.

**Comment by matt-gardner** [comment]
Can you tell me what huggingface model this failed with?

**Comment by OhadRubin** [comment]
distilbert-base-uncased

**Comment by matt-gardner** [comment]
It looks like you're using an older version of huggingface code; can you update and verify that you still see a problem with latest versions of allennlp and transformers?  If this doesn't work with distilbert, we'd like to know about it.
